[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    strategy: 투자 전략 관련 테스트
    login: 로그인 관련 테스트
    investment: 투자 관련 테스트
    sanity: 기본 동작 검증 테스트